import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ConstantesService {
  public readonly CHAVE_ARMAZENAMENTO = 'dados-lista-precos';
  public readonly NOME_APLICACAO = 'Lista de Preços';
  public readonly VERSAO = '1.0.0';

  public readonly PRODUTOS: string[] = [
    'Abacate KG',
    'Abacaxi UN',
    'Abóbora Cabotiá KG',
    'Abóbora Moranga KG',
    'Abóbora Seca KG',
    'Abóbora Verde KG',
    'Acelga UN',
    'Agrião UN',
    'Alecrim UN',
    'Alface Americana UN',
    'Alface Crespa UN',
    'Alface Lisa UN',
    'Alface Roxa UN',
    'Alho Poró UN',
    'Ameixa KG',
    'Batata Chips 300g',
    'Batata Escovada SC 25KG',
    'Batata Florão SC 25KG',
    'Batata Lavada SC 25KG',
    'Batata M SC 25KG',
    'Batata Palha KG',
    'Batata Palha Fritura SC 25KG',
    'Batata Roxa SC 25KG',
    'Batata-Doce Boa CX 20KG',
    'Batata-Doce G CX 20KG',
    'Batata-Doce P CX 20KG',
    'Berinjela KG',
    'Beterraba G CX 20KG',
    'Beterraba M CX 20KG',
    'Beterraba P CX 20KG',
    'Brócolis UN',
    'Caqui KG',
    'Cebola C1 SC 20KG',
    'Cebola C2 SC 20KG',
    'Cebola C3 SC 20KG',
    'Cebola C4 SC 20KG',
    'Cebola Fraca SC 20KG',
    'Cebola Roxa SC 20KG',
    'Cebolinha UN',
    'Cenoura Boa CX 20KG',
    'Cenoura G CX 20KG',
    'Cenoura M CX 20KG',
    'Cenoura Toco CX 20KG',
    'Chicória UN',
    'Chuchu CX 20KG',
    'Couve-Flor UN',
    'Feijão Preto SC 30KG',
    'Feijão Vermelho SC 30KG',
    'Gengibre KG',
    'Hortelã UN',
    'Kiwi KG',
    'Laranja CX 20KG',
    'Limão Caipira KG',
    'Limão Comum KG',
    'Limão Siciliano KG',
    'Maçã Argentina KG',
    'Maçã Fuji KG',
    'Maçã Gala KG',
    'Maçã Pink KG',
    'Maçã Verde KG',
    'Mamão Formosa KG',
    'Mamão Havaí KG',
    'Manga Espada KG',
    'Manga Palmer KG',
    'Manga Tommy KG',
    'Manjericão UN',
    'Maracujá KG',
    'Melão KG',
    'Morango CX 4 BDJ',
    'Nabo KG',
    'Nectarina KG',
    'Ovos BDJ CX',
    'Ovos Embalados CX',
    'Pepino CX 20KG',
    'Pepino Japonês CX 20KG',
    'Pera KG',
    'Pêssego KG',
    'Pimenta Dedo de Moça KG',
    'Pimentão Amarelo KG',
    'Pimentão Verde KG',
    'Pimentão Vermelho KG',
    'Rabanete KG',
    'Repolho Roxo UN',
    'Repolho Verde UN',
    'Rúcula UN',
    'Salsa UN',
    'Tangerina KG',
    'Tomate Cereja KG',
    'Tomate G CX 20KG',
    'Tomate M CX 20KG',
    'Tomate Saladette CX 20KG',
    'Uva Benitaka KG',
    'Uva Itália KG',
    'Uva Niágara KG',
    'Uva Ruby KG',
    'Uva Sem Semente BDJ',
    'Uva Sem Semente Preta BDJ',
    'Uva Sem Semente Verde BDJ',
    'Vagem KG',
  ];

  /**
   * Gera um ID único para um produto baseado no nome
   */
  public gerarIdProduto(nomeProduto: string): string {
    return nomeProduto
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^\w-]/g, '');
  }
}
